@@ -0,0 +1,45 @@
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '22.0.1+8'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
        continue-on-error: true
      - name: Display Gradle Logs
        if: failure()
        run: cat build/app/outputs/flutter-apk/*.log

      - name: Push to Releases
        if: success()
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
        env:
          JAVA_HOME: /Users/runner/hostedtoolcache/Java_Zulu_jdk/22.0.1-8/arm64
          JAVA_HOME_22_ARM64: /Users/runner/hostedtoolcache/Java_Zulu_jdk/22.0.1-8/arm64
          FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.22.2-x64
          PUB_CACHE: /Users/runner/.pub-cache
